"""50건의 복지 정책 샘플 데이터"""

WELFARE_POLICIES = [
    {
        "id": "POL-001",
        "name": "기초연금",
        "category": "노인",
        "target": "만 65세 이상 소득 하위 70% 노인",
        "benefit": "월 최대 334,810원 지급 (2024년 기준, 부부 수급 시 각 20% 감액)",
        "eligibility": "만 65세 이상, 가구 소득인정액이 선정기준액 이하 (단독가구 2,130,000원, 부부가구 3,408,000원, 2024년 기준)",
        "required_docs": ["주민등록등본", "금융정보 제공 동의서", "신분증"],
        "application": "주민센터 방문 또는 복지로(www.bokjiro.go.kr) 온라인 신청",
        "department": "보건복지부",
        "renewal": "매년 재확인",
    },
    {
        "id": "POL-002",
        "name": "국민기초생활보장 생계급여",
        "category": "저소득",
        "target": "기준 중위소득 30% 이하 가구",
        "benefit": "생계급여 = 생계급여 최저보장수준(기준 중위소득 30%) - 소득인정액",
        "eligibility": "소득인정액이 기준 중위소득 30% 이하, 부양의무자 기준 충족",
        "required_docs": ["주민등록등본", "소득·재산 신고서", "금융정보 제공 동의서"],
        "application": "주민센터 방문 신청",
        "department": "보건복지부",
        "renewal": "매년",
    },
    {
        "id": "POL-003",
        "name": "장애인연금",
        "category": "장애인",
        "target": "만 18세 이상 중증장애인 중 소득 하위 70%",
        "benefit": "기초급여 월 최대 323,180원 + 부가급여",
        "eligibility": "만 18세 이상 등록 중증장애인(1·2급, 3급 중복), 소득인정액 기준 이하",
        "required_docs": ["장애인등록증", "주민등록등본", "금융정보 제공 동의서"],
        "application": "주민센터 또는 복지로 신청",
        "department": "보건복지부",
        "renewal": "매년",
    },
    {
        "id": "POL-004",
        "name": "아동수당",
        "category": "아동·영유아",
        "target": "만 8세 미만 아동",
        "benefit": "월 10만원",
        "eligibility": "대한민국 국적, 주민등록 아동 (만 0세~7세)",
        "required_docs": ["아동 출생신고 완료", "주민등록등본", "신청인 신분증"],
        "application": "복지로, 정부24, 주민센터 방문",
        "department": "보건복지부",
        "renewal": "만 8세 생일 전월까지 자동 지급",
    },
    {
        "id": "POL-005",
        "name": "부모급여",
        "category": "아동·영유아",
        "target": "만 0~1세 영아",
        "benefit": "0세 월 100만원, 1세 월 50만원 (어린이집 이용 시 보육료 바우처로 지급, 차액 현금 지급)",
        "eligibility": "대한민국 국적 만 0~23개월 아동 (소득·재산 무관)",
        "required_docs": ["출생증명서 또는 출생신고 완료", "주민등록등본", "통장 사본"],
        "application": "복지로(www.bokjiro.go.kr), 정부24, 주민센터 방문 (출생 후 60일 이내 신청 권장)",
        "department": "보건복지부",
        "renewal": "24개월까지 자동 지급",
    },
    {
        "id": "POL-006",
        "name": "청년 내일저축계좌",
        "category": "청년",
        "target": "소득 기준 중위소득 100% 이하 청년 근로자",
        "benefit": "본인 저축 10만원/월 시 정부 매칭 10만원(중위소득 50% 초과~100%) 또는 30만원(수급자·차상위) 추가 적립. 3년 만기 시 최대 1,440만원",
        "eligibility": "만 19~34세 (수급자·차상위 15~39세), 근로·사업소득 있는 청년, 기준 중위소득 100% 이하, 재산 6억원 이하",
        "required_docs": ["주민등록등본", "근로소득원천징수영수증 또는 사업소득 확인서류", "통장 사본"],
        "application": "복지로(www.bokjiro.go.kr) 온라인 신청 (연 1회 모집, 매년 6~7월)",
        "department": "보건복지부",
        "renewal": "3년 만기",
    },
    {
        "id": "POL-007",
        "name": "첫만남이용권",
        "category": "아동·영유아",
        "target": "출생 아동 (2022년 1월 1일 이후 출생)",
        "benefit": "첫째 200만원, 둘째 이상 300만원 국민행복카드 바우처 (출생 후 1년 내 사용)",
        "eligibility": "2022년 1월 1일 이후 출생아, 주민등록 등재 아동 (소득·재산 무관)",
        "required_docs": ["출생신고 완료", "주민등록등본", "신청인 신분증"],
        "application": "복지로(www.bokjiro.go.kr), 정부24, 주민센터 방문 (출생 후 60일 이내 신청)",
        "department": "보건복지부",
        "renewal": "1회 (출생 후 1년 이내 사용)",
    },
    {
        "id": "POL-008",
        "name": "국민취업지원제도 I 유형",
        "category": "취업지원",
        "target": "저소득 구직자",
        "benefit": "구직촉진수당 월 50만원 × 6개월 + 취업지원서비스",
        "eligibility": "만 15~69세, 가구 소득 중위 60% 이하, 재산 4억원 이하, 취업경험 100일 이상",
        "required_docs": ["주민등록등본", "가구원 소득·재산 확인서류", "취업경험 확인서류"],
        "application": "워크넷 또는 고용센터 방문",
        "department": "고용노동부",
        "renewal": "1회",
    },
    {
        "id": "POL-009",
        "name": "청년 월세 한시 특별지원",
        "category": "청년",
        "target": "독립 거주 청년",
        "benefit": "월 최대 20만원 × 12개월",
        "eligibility": "만 19~34세, 부모와 독립 거주, 임차보증금 5,000만원·월세 60만원 이하, 청년 소득 기준 중위 60% 이하",
        "required_docs": ["임대차계약서", "주민등록등본", "가족관계증명서", "소득 증빙서류"],
        "application": "복지로 온라인 신청",
        "department": "국토교통부",
        "renewal": "12개월 한시",
    },
    {
        "id": "POL-010",
        "name": "노인 일자리 및 사회활동 지원",
        "category": "노인",
        "target": "만 65세 이상 어르신",
        "benefit": "활동비 월 27만원~40만원 (유형별 상이)",
        "eligibility": "만 65세 이상 (공익활동형은 기초연금 수급자 우선), 건강 상태 양호",
        "required_docs": ["주민등록등본", "신분증", "건강진단서"],
        "application": "주민센터 또는 시니어클럽, 노인복지관 방문",
        "department": "보건복지부",
        "renewal": "매년 신청",
    },
    {
        "id": "POL-011",
        "name": "장애인 활동지원서비스",
        "category": "장애인",
        "target": "만 6세 이상 65세 미만 중증장애인",
        "benefit": "월 최대 활동지원 1,853천원어치 바우처",
        "eligibility": "장애인복지법상 등록장애인, 활동지원 인정점수 42점 이상",
        "required_docs": ["장애인등록증", "주민등록등본", "의사소견서"],
        "application": "주민센터 방문",
        "department": "보건복지부",
        "renewal": "매년 갱신",
    },
    {
        "id": "POL-012",
        "name": "한부모가족 아동양육비",
        "category": "한부모가족",
        "target": "한부모가족 만 18세 미만 자녀",
        "benefit": "자녀 1인당 월 21만원",
        "eligibility": "소득인정액 기준 중위소득 63% 이하 한부모·조손가족",
        "required_docs": ["가족관계증명서", "주민등록등본", "소득·재산 신고서"],
        "application": "주민센터 방문",
        "department": "여성가족부",
        "renewal": "매년",
    },
    {
        "id": "POL-013",
        "name": "교육급여 (기초생활보장)",
        "category": "교육",
        "target": "기준 중위소득 50% 이하 가구 학생",
        "benefit": "초등 461,000원, 중등 654,000원, 고등 727,000원 (연간)",
        "eligibility": "소득인정액이 기준 중위소득 50% 이하, 초·중·고 재학생",
        "required_docs": ["재학증명서", "주민등록등본", "소득·재산 신고서"],
        "application": "복지로 또는 주민센터",
        "department": "교육부",
        "renewal": "매년",
    },
    {
        "id": "POL-014",
        "name": "의료급여 1종",
        "category": "의료",
        "target": "기초생활수급자 중 근로 능력 없는 자",
        "benefit": "입·외래 본인부담금 면제 또는 정액",
        "eligibility": "생계·의료급여 수급자 중 1종 해당자 (노인, 장애인, 영·유아 등)",
        "required_docs": ["의료급여증", "주민등록등본"],
        "application": "주민센터 자동 발급",
        "department": "보건복지부",
        "renewal": "수급자격 유지 시 자동",
    },
    {
        "id": "POL-015",
        "name": "실업급여 (구직급여)",
        "category": "고용",
        "target": "비자발적 실직 근로자",
        "benefit": "이직 전 평균임금의 60% × 소정급여일수 (최소 120일~최대 270일)",
        "eligibility": "고용보험 피보험단위기간 180일 이상, 비자발적 이직, 적극적 재취업 활동",
        "required_docs": ["이직확인서", "고용보험 피보험자격 이력내역서"],
        "application": "고용24 온라인 또는 고용센터 방문",
        "department": "고용노동부",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-016",
        "name": "출산 전후 휴가급여",
        "category": "모성보호",
        "target": "출산한 고용보험 피보험 근로자",
        "benefit": "통상임금 100% × 90일 (다태아 120일)",
        "eligibility": "출산 전 고용보험 피보험자, 출산 전후 휴가 사용",
        "required_docs": ["출산 전후 휴가 확인서", "통상임금 확인 서류"],
        "application": "고용24 온라인 또는 고용센터",
        "department": "고용노동부",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-017",
        "name": "육아휴직급여",
        "category": "모성보호",
        "target": "만 8세 이하 자녀 육아휴직 근로자",
        "benefit": "통상임금 80% (상한 150만원, 하한 70만원) × 최대 12개월",
        "eligibility": "고용보험 피보험자, 만 8세 이하 또는 초등 2학년 이하 자녀",
        "required_docs": ["육아휴직 확인서", "자녀 주민등록등본"],
        "application": "고용24 온라인",
        "department": "고용노동부",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-018",
        "name": "노인 맞춤돌봄서비스",
        "category": "노인",
        "target": "만 65세 이상 독거·고령 노인",
        "benefit": "안전·건강·일상생활 지원 서비스 (방문, 통원 등)",
        "eligibility": "만 65세 이상 독거노인, 장애 및 고립 위험 노인 (기초생활수급자·차상위 우선)",
        "required_docs": ["주민등록등본", "신분증", "의사소견서 (필요 시)"],
        "application": "주민센터 또는 노인복지관 방문",
        "department": "보건복지부",
        "renewal": "매년",
    },
    {
        "id": "POL-019",
        "name": "청소년 산모 임신·출산 의료비 지원",
        "category": "임산부",
        "target": "만 18세 이하 청소년 산모",
        "benefit": "임신·출산 의료비 120만원 이내 국민행복카드 지원",
        "eligibility": "만 18세 이하 임신 청소년 산모",
        "required_docs": ["임신확인서", "주민등록등본"],
        "application": "국민건강보험공단 또는 사회서비스 전자바우처",
        "department": "보건복지부",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-020",
        "name": "에너지바우처",
        "category": "저소득",
        "target": "에너지 취약 계층",
        "benefit": "여름·겨울 냉난방비 바우처 (1인 가구 138,700원~)",
        "eligibility": "기초생활 수급자(생계·의료급여) 중 노인, 영유아, 장애인, 임산부, 중증질환자 포함 가구",
        "required_docs": ["주민등록등본", "수급자 확인서"],
        "application": "주민센터 방문",
        "department": "산업통상자원부",
        "renewal": "매년",
    },
    {
        "id": "POL-021",
        "name": "장애아동 발달재활서비스",
        "category": "장애아동",
        "target": "만 18세 미만 장애아동",
        "benefit": "월 14만원~22만원 바우처 (소득수준별 차등)",
        "eligibility": "만 18세 미만 등록 장애아동, 기준 중위소득 180% 이하",
        "required_docs": ["장애인등록증", "주민등록등본", "소득 증빙"],
        "application": "주민센터 방문",
        "department": "보건복지부",
        "renewal": "매년",
    },
    {
        "id": "POL-022",
        "name": "임신·출산 진료비 지원 (국민행복카드)",
        "category": "임산부",
        "target": "건강보험 가입 임산부",
        "benefit": "임신·출산 진료비 100만원 (다태아 140만원)",
        "eligibility": "건강보험 가입자 또는 피부양자로 임신 확인",
        "required_docs": ["임신확인서", "신분증"],
        "application": "건강보험공단 또는 은행 신청",
        "department": "보건복지부",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-023",
        "name": "긴급복지지원 생계지원",
        "category": "긴급지원",
        "target": "갑작스러운 위기상황 저소득 가구",
        "benefit": "4인 가구 기준 월 183만원 (최대 6회)",
        "eligibility": "갑작스러운 실직, 사망, 화재 등 위기사유 발생, 소득·재산 기준 충족",
        "required_docs": ["위기 상황 증빙서류", "주민등록등본", "금융정보 제공 동의서"],
        "application": "주민센터 또는 129 복지콜센터",
        "department": "보건복지부",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-024",
        "name": "청년 창업 지원금 (창업성공패키지)",
        "category": "청년창업",
        "target": "만 39세 이하 예비창업자·초기창업자",
        "benefit": "사업화 자금 최대 1억원 + 창업교육·멘토링",
        "eligibility": "만 39세 이하, 창업 3년 이내 (예비창업자 포함)",
        "required_docs": ["사업계획서", "신분증", "사업자등록증 (해당 시)"],
        "application": "K-스타트업 온라인 신청",
        "department": "중소벤처기업부",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-025",
        "name": "노인 장기요양서비스",
        "category": "노인",
        "target": "65세 이상 또는 노인성 질환자",
        "benefit": "재가급여(방문요양 등) 또는 시설급여, 등급별 월 한도액 이내",
        "eligibility": "장기요양 1~5등급 또는 인지지원등급 판정",
        "required_docs": ["장기요양인정서", "의사소견서"],
        "application": "국민건강보험공단 신청",
        "department": "보건복지부",
        "renewal": "인정기간 종료 전 갱신",
    },
    {
        "id": "POL-026",
        "name": "주거급여 (기초생활보장)",
        "category": "주거",
        "target": "기준 중위소득 48% 이하 가구",
        "benefit": "임차급여: 지역별 기준임대료 이하 실지급 / 자가급여: 수선유지비 지원",
        "eligibility": "소득인정액 기준 중위소득 48% 이하",
        "required_docs": ["임대차계약서", "주민등록등본", "소득·재산 신고서"],
        "application": "주민센터 방문",
        "department": "국토교통부",
        "renewal": "매년",
    },
    {
        "id": "POL-027",
        "name": "청년 전세대출 (청년버팀목전세자금)",
        "category": "청년주거",
        "target": "만 34세 이하 무주택 청년",
        "benefit": "보증금 2억원 이내 연 1.8%~2.7% 저금리 대출",
        "eligibility": "만 19~34세 무주택자, 부부합산 연소득 5,000만원 이하",
        "required_docs": ["임대차계약서", "주민등록등본", "가족관계증명서", "소득 증빙"],
        "application": "주택도시기금 수탁은행 방문",
        "department": "국토교통부",
        "renewal": "2년 (최대 10년)",
    },
    {
        "id": "POL-028",
        "name": "자활 근로 사업",
        "category": "저소득",
        "target": "근로능력 있는 생계·의료·주거·교육급여 수급자 및 차상위계층",
        "benefit": "시장진입형 월 최대 197만원, 사회서비스형 월 최대 167만원",
        "eligibility": "근로능력 있는 수급자 및 차상위계층",
        "required_docs": ["주민등록등본", "소득·재산 신고서"],
        "application": "지역자활센터 방문",
        "department": "보건복지부",
        "renewal": "매년",
    },
    {
        "id": "POL-029",
        "name": "차상위 본인부담경감 의료비 지원",
        "category": "의료",
        "target": "차상위계층",
        "benefit": "건강보험 본인부담금 경감 (외래 1,000~2,000원)",
        "eligibility": "소득인정액 기준 중위소득 50% 이하 차상위계층",
        "required_docs": ["주민등록등본", "소득·재산 확인서"],
        "application": "주민센터 방문",
        "department": "보건복지부",
        "renewal": "매년",
    },
    {
        "id": "POL-030",
        "name": "문화누리카드",
        "category": "문화",
        "target": "기초생활수급자·차상위계층",
        "benefit": "연 13만원 문화·여행·체육 사용 바우처",
        "eligibility": "기초생활수급자, 차상위계층 (6세 이상)",
        "required_docs": ["수급자 확인서 또는 차상위 확인서", "신분증"],
        "application": "읍면동 주민센터 또는 문화누리 온라인",
        "department": "문화체육관광부",
        "renewal": "매년",
    },
    {
        "id": "POL-031",
        "name": "청소년 특별지원",
        "category": "청소년",
        "target": "만 9~24세 위기청소년",
        "benefit": "생활비 월 최대 65만원, 의료비·학업비·자립지원비 등",
        "eligibility": "위기청소년으로 판단되는 만 9~24세, 소득 기준 중위소득 72% 이하",
        "required_docs": ["주민등록등본", "학교재학확인서 (해당 시)", "소득 증빙"],
        "application": "청소년상담복지센터 또는 주민센터",
        "department": "여성가족부",
        "renewal": "매년",
    },
    {
        "id": "POL-032",
        "name": "산재 근로자 요양급여",
        "category": "산재",
        "target": "업무상 재해를 당한 근로자",
        "benefit": "치료비 전액 지원",
        "eligibility": "업무상 재해 또는 직업병 인정",
        "required_docs": ["요양급여신청서", "초진소견서", "재해경위서"],
        "application": "근로복지공단 방문 또는 온라인",
        "department": "고용노동부",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-033",
        "name": "희귀질환자 의료비 지원",
        "category": "의료",
        "target": "희귀질환 환자",
        "benefit": "요양급여 본인부담금 최대 90% 지원",
        "eligibility": "희귀질환자 산정특례 등록자, 소득기준 중위소득 130% 이하",
        "required_docs": ["진단서", "주민등록등본", "소득 증빙"],
        "application": "국민건강보험공단 또는 보건소",
        "department": "보건복지부",
        "renewal": "매년",
    },
    {
        "id": "POL-034",
        "name": "고령자 고용장려금",
        "category": "노인고용",
        "target": "60세 이상 고령자 고용 사업주",
        "benefit": "근로자 1인당 월 30만원 (최대 1년)",
        "eligibility": "60세 이상 근로자를 월 평균 60시간 이상 고용한 사업주",
        "required_docs": ["사업자등록증", "고용 근로자 명부", "임금대장"],
        "application": "고용센터 또는 고용24 온라인",
        "department": "고용노동부",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-035",
        "name": "한국장학재단 국가장학금 I 유형",
        "category": "교육",
        "target": "대학생 (소득분위 8구간 이하)",
        "benefit": "연 최대 520만원 (소득분위별 차등)",
        "eligibility": "국내 대학 재학생, 소득분위 8구간 이하, 성적 기준 충족",
        "required_docs": ["재학증명서", "가족관계증명서", "소득 증빙"],
        "application": "한국장학재단 온라인 (매 학기)",
        "department": "교육부",
        "renewal": "매 학기",
    },
    {
        "id": "POL-036",
        "name": "다자녀 양육비 지원 (셋째아 이상)",
        "category": "다자녀",
        "target": "셋째 이상 자녀 양육 가정",
        "benefit": "월 30만원 (지자체별 상이)",
        "eligibility": "셋째 이상 자녀, 주민등록 기준 해당 지자체 거주",
        "required_docs": ["가족관계증명서", "주민등록등본"],
        "application": "주민센터 방문",
        "department": "각 지자체",
        "renewal": "자녀 만 7세까지",
    },
    {
        "id": "POL-037",
        "name": "노인 무릎 인공관절 수술비 지원",
        "category": "노인의료",
        "target": "만 60세 이상 의료급여 수급자 또는 차상위계층",
        "benefit": "무릎 인공관절 수술비 본인부담금 전액 지원",
        "eligibility": "만 60세 이상, 의료급여 1·2종 또는 차상위 건강보험 경감 대상자",
        "required_docs": ["진단서", "주민등록등본", "의료급여증"],
        "application": "수술 실시 의료기관 → 국민건강보험공단",
        "department": "보건복지부",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-038",
        "name": "보육료 지원 (어린이집)",
        "category": "영유아보육",
        "target": "만 0~5세 어린이집 이용 아동",
        "benefit": "0세 월 514,000원, 1세 월 452,000원, 2세 월 375,000원, 3~5세 월 280,000원 (2024년 기준, 소득무관)",
        "eligibility": "대한민국 국적 만 0~5세 아동, 어린이집 이용 (소득·재산 무관)",
        "required_docs": ["주민등록등본", "신분증"],
        "application": "복지로(www.bokjiro.go.kr) 온라인 또는 어린이집 직접 신청",
        "department": "보건복지부",
        "renewal": "만 5세까지 자동",
    },
    {
        "id": "POL-039",
        "name": "유아학비 지원 (유치원)",
        "category": "교육",
        "target": "만 3~5세 유치원 이용 아동",
        "benefit": "월 최대 28만원 유아학비 지원",
        "eligibility": "만 3~5세 유치원 재원 아동 (소득무관)",
        "required_docs": ["주민등록등본"],
        "application": "유치원 입학 후 자동 신청",
        "department": "교육부",
        "renewal": "만 5세까지 자동",
    },
    {
        "id": "POL-040",
        "name": "청년 도약계좌",
        "category": "청년",
        "target": "총급여 7,500만원 이하 청년",
        "benefit": "월 최대 70만원 납입, 정부기여금 월 최대 24,000원, 이자 비과세. 5년 만기 시 최대 5,000만원 목돈 마련",
        "eligibility": "만 19~34세, 개인소득 7,500만원 이하, 가구소득 중위소득 180% 이하 (병역 이행자 병역기간 제외)",
        "required_docs": ["신분증", "소득 확인서류 (건강보험료 납부확인서 등)"],
        "application": "취급 은행 앱 또는 영업점 방문 (매월 모집)",
        "department": "금융위원회",
        "renewal": "5년 만기",
    },
    {
        "id": "POL-041",
        "name": "장애인 편의시설 설치 지원",
        "category": "장애인",
        "target": "장애인 가구",
        "benefit": "편의시설 설치비 380만원 이내 지원",
        "eligibility": "등록 장애인, 자가 소유 또는 임차인 동의",
        "required_docs": ["장애인등록증", "주민등록등본", "건물 등기부등본"],
        "application": "주민센터 또는 한국장애인개발원",
        "department": "보건복지부",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-042",
        "name": "노인 틀니·임플란트 건강보험 급여",
        "category": "노인의료",
        "target": "만 65세 이상 건강보험 가입자",
        "benefit": "틀니 본인부담 30%, 임플란트 2개 본인부담 30%",
        "eligibility": "만 65세 이상 건강보험 가입자",
        "required_docs": ["건강보험증"],
        "application": "치과 방문 시 자동 적용",
        "department": "보건복지부",
        "renewal": "7년에 1회",
    },
    {
        "id": "POL-043",
        "name": "발달장애인 낮활동 서비스",
        "category": "장애인",
        "target": "만 18세 이상 성인 발달장애인",
        "benefit": "주간활동서비스 월 100시간~200시간",
        "eligibility": "만 18세 이상 지적·자폐성 장애인 (장애인 활동지원 미수급자)",
        "required_docs": ["장애인등록증", "주민등록등본"],
        "application": "주민센터 방문",
        "department": "보건복지부",
        "renewal": "매년",
    },
    {
        "id": "POL-044",
        "name": "청년 구직활동 지원금",
        "category": "청년취업",
        "target": "졸업·중퇴 후 미취업 청년",
        "benefit": "월 50만원 × 6개월",
        "eligibility": "만 18~34세, 학교 졸업·중퇴 후 2년 이내, 미취업, 가구 중위소득 120% 이하",
        "required_docs": ["졸업(중퇴)증명서", "주민등록등본", "소득 증빙"],
        "application": "워크넷 온라인",
        "department": "고용노동부",
        "renewal": "6개월 1회",
    },
    {
        "id": "POL-045",
        "name": "저소득 한부모가족 법률구조 지원",
        "category": "한부모가족",
        "target": "한부모가족",
        "benefit": "법률 상담, 소송 대리 무료 지원",
        "eligibility": "한부모가족지원법상 한부모가족",
        "required_docs": ["가족관계증명서", "한부모 확인서"],
        "application": "대한법률구조공단 신청",
        "department": "여성가족부",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-046",
        "name": "사회적 기업 일자리창출사업",
        "category": "취업지원",
        "target": "사회적 기업 고용 취약계층 근로자",
        "benefit": "인건비 최저임금의 80~100% 지원 (최대 3년)",
        "eligibility": "인증 사회적 기업, 고용 근로자가 취약계층",
        "required_docs": ["사회적기업 인증서", "근로계약서"],
        "application": "고용센터",
        "department": "고용노동부",
        "renewal": "매년",
    },
    {
        "id": "POL-047",
        "name": "통합문화이용권 (장애인)",
        "category": "장애인문화",
        "target": "기초생활수급 장애인",
        "benefit": "연 13만원 문화·여행·체육 바우처",
        "eligibility": "기초생활수급 장애인 (6세 이상)",
        "required_docs": ["장애인등록증", "수급자 확인서"],
        "application": "주민센터 또는 문화누리 온라인",
        "department": "문화체육관광부",
        "renewal": "매년",
    },
    {
        "id": "POL-048",
        "name": "농어촌 출산지원금",
        "category": "농어촌출산",
        "target": "농어촌 지역 출산 가정",
        "benefit": "첫째 300만원, 둘째 500만원, 셋째 이상 700만원 (지자체별 상이)",
        "eligibility": "농어촌 지역 6개월 이상 거주, 신생아 출생",
        "required_docs": ["출생증명서", "주민등록등본", "6개월 이상 거주 확인서"],
        "application": "읍면 주민센터 방문",
        "department": "각 지자체",
        "renewal": "해당 없음",
    },
    {
        "id": "POL-049",
        "name": "청년 정신건강 지원 (마음이음)",
        "category": "청년정신건강",
        "target": "만 19~34세 청년",
        "benefit": "심리상담 6회 지원 (회당 약 8만원 상당)",
        "eligibility": "만 19~34세 청년, 소득기준 없음",
        "required_docs": ["신분증"],
        "application": "정신건강복지센터 또는 청년마음건강지원사업 온라인",
        "department": "보건복지부",
        "renewal": "연 1회",
    },
    {
        "id": "POL-050",
        "name": "저소득층 기저귀·조제분유 지원",
        "category": "영유아",
        "target": "저소득 가구 영아",
        "benefit": "기저귀 월 64,000원 + 조제분유 월 86,000원 바우처",
        "eligibility": "만 24개월 미만 영아, 기준 중위소득 80% 이하 (기저귀), 모유수유 불가 시 조제분유 추가",
        "required_docs": ["주민등록등본", "건강보험료 납부확인서", "출생증명서"],
        "application": "복지로 온라인 또는 주민센터",
        "department": "보건복지부",
        "renewal": "만 24개월까지",
    },
]
